# Generated by Django 3.1.7 on 2021-03-24 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('inum', models.IntegerField(default=0)),
                ('due_date', models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 24, 9, 23, 50, 688247, tzinfo=utc))),
                ('active', models.BooleanField(default=False)),
                ('chapter', models.IntegerField(default=0)),
            ],
        ),
    ]
