# Generated by Django 3.1.7 on 2021-03-31 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spelling', '0003_auto_20210330_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 6, 35, 40, 633232, tzinfo=utc)),
        ),
    ]
