# Generated by Django 3.1.7 on 2021-03-31 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spelling', '0004_auto_20210331_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='word',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 8, 13, 50, 742867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='word',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
