# Generated by Django 3.1.7 on 2021-04-01 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spelling', '0005_auto_20210331_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 9, 57, 53, 574978, tzinfo=utc)),
        ),
    ]
